baseline: Your blogging assistant
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: fuck u jessica
date:
  format: j F Y
  timezone: America/Chicago
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Jessica Jou
baseurl: /
canonicalurl: true
